version: '3'
services:
  app:
    container_name: nama-container
    build:
      context: .  # Direktori saat ini
      dockerfile: Dockerfile  # Gunakan Dockerfile yang telah Anda buat
    ports:
      - "8081:8080"  # Meneruskan port 8080 di host ke port 8080 di container
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dompetku
      MYSQL_USER: said
      MYSQL_PASSWORD: said
    ports:
      - "3307:3306"  # Meneruskan port 3306 di host ke port 3306 di container

networks:
  springnetwork:
    external: true
